FORMAT: 1A
HOST: http://kartverkettest.herokuapp.com

# kartverket/test
kartverket/test api is a sandbox for testing Lilly Labs' Kartverket REST APIs

# Group Administrative Units
Group related resources of the **kartverket/test API**

## Counties Collection [/counties]
### List all Counties [GET]
+ Response 200 (application/json)

        [
            {
                id: 20,
                name: {
                    no: "Finnmark",
                    se: "Finnmárku"
                },
                placename_uris: [
                    "/placename/123456789"
                ],
                geojson: "/geojson/county-20-1.geojson"
            }, {
                id: 19,
                name: {
                    no: "Troms",
                    se: "Romssa"
                },
                placename_uris: [
                    "/placename/987654321"
                ],
                geojson: "/geojson/county-19-1.geojson"
            }
        ]

## County [/counties/{id}]
A single County object with all its details

+ Parameters
    + id (required, number, `20`) ... Numeric `id` of the County to perform action with. Has example value.

### Retrieve a County summary [GET]
+ Response 200 (application/json)

        {
            id: 20,
            name: {
                nb: "Finnmark",
                nn: "Finnmark",
                se: "Finnmárku"
            },
            placename_uris: [
                "/placename/123456789"
            ],
            geojson: "/geojson/county-20-1.geojson"
        }
