FORMAT: 1A
HOST: http://kartverkettest.herokuapp.com

# kartverket/test api
kartverket/test api is a sandbox for testing Lilly Labs' Kartverket REST APIs

# Group Norwegian Administrative Units
Group related resources of the **kartverket/test API**

## Counties Collection [/counties]
### List all Counties [GET]
+ Response 200 (application/json)

        [
            {
                id: 20,
                name: {
                    no: "Finnmark",
                    se: "Finnmárku"
                },
                placename_uris: [
                    "/placename/123456789"
                ],
                geojson: "/geojson/county-20-1.geojson"
            }, {
                id: 19,
                name: {
                    no: "Troms",
                    se: "Romssa"
                },
                placename_uris: [
                    "/placename/987654321"
                ],
                geojson: "/geojson/county-19-1.geojson"
            }
        ]

## County [/counties/{id}]
A single County object with all its details

+ Parameters
    + id (required, number, `20`) ... Numeric `id` of the County to perform action with. Has example value.

### Retrieve a County summary [GET]
+ Response 200 (application/json)

        {
            id: 20,
            name: {
                nb: "Finnmark",
                nn: "Finnmark",
                se: "Finnmárku"
            },
            placename_uris: [
                "/placename/123456789"
            ],
            geojson: "/geojson/county-20-1.geojson"
        }

# Group Norwegian Placenames

## Placename [/placenames/{ssr_id}{?geojson}]
A single placename object

+ Parameters
    + id (required, number, `1234356`) ... Numeric `ìd` of the Placename in the 'Statens stedsnavnsregister' database. Has example value.

### Retrieve a Placename object [GET]
+ Response 200 (application/json)

        {
            "name_type_group":5,
            "name_type_code":108,
            "official_status":"G",
            "language_code":"NO",
            "ssr_id":1935,
            "display_name":"Hoggandvik",
            "municipality_code":"1002",
            "county_code":"010",
            "coordinates":[
                58.039100000000005,
                7.363375
            ]
        }
        
+ Response 200 (application/geojson)

        {
            "type":"Feature",
            "properties":{
                "id":3380
            },
            "geometry":{
                "type":"Point",
                "coordinates":[
                    5.860310999999999,
                    58.496517000000004
                ]
            }
        }